name: MC_Minigames_Plugin
version: '${project.version}'
main: mc_minigames_plugin.mc_minigames_plugin.MC_Minigames_Plugin
api-version: 1.19
authors: [ Miles, Kirt ]
description: A plugin built for the MC minigames server
commands:
  fly:
    description: Toggles flying for the command sender.
    usage: /fly
    aliases: f
    permission: fly
    permission-message: You do not have permission.
  hub:
    description: Teleports the command sender to the main hub.
    usage: /hub
  menu:
    description: Opens a custom menu
    usage: /menu
  setSpawn:
    description: Sets the server spawn
    usage: /setSpawn
    permission: spawn.set
  spawn:
    description: Teleports you to the server spawn
    usage: /spawn
    permission: spawn.teleport
  troubleshoot:
    description: Gives game dev troubleshooting abilities/tools
    usage: /troubleshoot
    permission: troubleshoot
  reset:
    description: Resets an MCPlayer's data
    usage: /reset <type> <username>
    permission: gameDev.reset
  getitem:
    usage: /getitem <item> <username>
    permission: getitem
